from django.db import models


#Criando as Class para o banco (Tentar Relacinar essas (  <!>  TABELAS)


class Administracao(models.Model):
    data_adm_operacional = models.DateField(auto_now_add=True)
    hora_adm_operacional = models.TimeField(auto_now_add=True)
    matricula_auditor_adm_operacional = models.IntegerField()
    nome_auditor_adm_operacional = models.CharField(max_length = 255)
    matricula_colaborador_adm_operacional =  models.IntegerField()
    nome_colaborador_adm_operacional = models.CharField(max_length=255)

    pergunta1_adm_operacional = models.CharField(max_length = 10)
    pergunta2_adm_operacional = models.CharField(max_length = 10)
    pergunta3_adm_operacional = models.CharField(max_length = 10)
    pergunta4_adm_operacional = models.CharField(max_length = 10)
    pergunta5_adm_operacional = models.CharField(max_length = 10)
    pergunta6_adm_operacional = models.CharField(max_length = 10)
    pergunta7_adm_operacional = models.CharField(max_length = 10)
    pergunta8_adm_operacional = models.CharField(max_length = 10)
    pergunta9_adm_operacional = models.CharField(max_length = 10)
    pergunta10_adm_operacional = models.CharField(max_length = 10)
    pergunta11_adm_operacional = models.CharField(max_length = 10)
    pergunta12_adm_operacional = models.CharField(max_length = 10)
    pergunta13_adm_operacional = models.CharField(max_length = 10)
    pergunta14_adm_operacional = models.CharField(max_length = 10)
    pergunta15_adm_operacional = models.CharField(max_length = 10)

 
class CaminhaoOficina(models.Model):
    data_caminhao_oficina = models.DateField(auto_now_add=True)
    hora_caminhao_oficina = models.TimeField(auto_now_add=True)
    matricula_auditor_caminhao_oficina = models.IntegerField()
    nome_auditor_caminhao_oficina = models.CharField(max_length = 255)
    matricula_colaborador_caminhao_oficina = models.IntegerField()
    nome_colaborador_caminhao_oficina = models.CharField(max_length = 255)

    pergunta1_caminhao_oficina = models.CharField(max_length = 10)
    pergunta2_caminhao_oficina = models.CharField(max_length = 10)
    pergunta3_caminhao_oficina = models.CharField(max_length = 10)
    pergunta4_caminhao_oficina = models.CharField(max_length = 10)
    pergunta5_caminhao_oficina = models.CharField(max_length = 10)
    pergunta6_caminhao_oficina = models.CharField(max_length = 10)
    pergunta7_caminhao_oficina = models.CharField(max_length = 10)
    pergunta8_caminhao_oficina = models.CharField(max_length = 10)
    pergunta9_caminhao_oficina = models.CharField(max_length = 10)
    pergunta10_caminhao_oficina = models.CharField(max_length = 10)
    pergunta11_caminhao_oficina = models.CharField(max_length = 10)
    pergunta12_caminhao_oficina = models.CharField(max_length = 10)
    pergunta13_caminhao_oficina = models.CharField(max_length = 10)
    pergunta14_caminhao_oficina = models.CharField(max_length = 10)
    pergunta15_caminhao_oficina = models.CharField(max_length = 10)

class industria(models.Model):
    data_industria = models.DateTimeField(auto_now_add = True)
    hora_industria = models.TimeField(auto_now_add = True)
    matricula_auditor_industria = models.IntegerField()
    nome_auditor_industria = models.CharField(max_length = 255)
    matricula_colaborador_industria = models.IntegerField()
    nome_colaborador_industria = models.CharField(max_length = 255)

    pergunta1_industria = models.CharField(max_length = 10)
    pergunta2_industria = models.CharField(max_length = 10)
    pergunta3_industria = models.CharField(max_length = 10)
    pergunta4_industria = models.CharField(max_length = 10)
    pergunta5_industria = models.CharField(max_length = 10)
    pergunta6_industria = models.CharField(max_length = 10)
    pergunta7_industria = models.CharField(max_length = 10)
    pergunta8_industria = models.CharField(max_length = 10)
    pergunta9_industria = models.CharField(max_length = 10)
    pergunta10_industria = models.CharField(max_length = 10)
    pergunta11_industria = models.CharField(max_length = 10)
    pergunta12_industria = models.CharField(max_length = 10)
    pergunta13_industria = models.CharField(max_length = 10)
    pergunta14_industria = models.CharField(max_length = 10)
    pergunta15_industria = models.CharField(max_length = 10)

class Automotiva(models.Model):
    data_automotiva = models.DateField()
    hora_automotiva = models.TimeField()
    matricula_auditor_automotiva = models.IntegerField()
    nome_auditor_automotiva = models.CharField(max_length = 255)
    matricula_colaborador_automotiva = models.IntegerField()
    nome_colaborador_automotiva = models.CharField(max_length = 255)

    pergunta1_automotiva = models.CharField(max_length = 10)
    pergunta2_automotiva = models.CharField(max_length = 10)
    pergunta3_automotiva = models.CharField(max_length = 10)
    pergunta4_automotiva = models.CharField(max_length = 10)
    pergunta5_automotiva = models.CharField(max_length = 10)
    pergunta6_automotiva = models.CharField(max_length = 10)
    pergunta7_automotiva = models.CharField(max_length = 10)
    pergunta8_automotiva = models.CharField(max_length = 10)
    pergunta9_automotiva = models.CharField(max_length = 10)
    pergunta10_automotiva = models.CharField(max_length = 10)
    pergunta11_automotiva = models.CharField(max_length = 10)
    pergunta12_automotiva = models.CharField(max_length = 10) 
    pergunta13_automotiva = models.CharField(max_length = 10)
    pergunta14_automotiva = models.CharField(max_length = 10)
    pergunta15_automotiva = models.CharField(max_length = 10)

